name = "Hugo Theme Community"
license = "MIT"
licenselink = "https://github.com/ifosch/hugo-theme-community/blob/master/LICENSE"
description = ""
homepage = "https://github.com/ifosch/hugo-theme-community/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Ignasi Fosch"
  homepage = "https://natx.cat"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
